Repository atomist/sdm, pull requests merged in 2018-08, with the labels that each got.

#483 Specific logging on cleanup of cached project
  src/api-helper/project/CachingProjectLoader.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#485 Print more on diff error
  src/api-helper/misc/git/filesChangedSince.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#497 Fix incorrect print statement
  src/api-helper/misc/git/filesChangedSince.ts
Labels: auto-merge:on-approve, changelog:fixed

#498 Add IsPushToBranchWithPullRequest push test
  package-lock.json
  package.json
  src/api/mapping/support/commonPushTests.ts
  src/graphql/query/PullRequestsForBranch.graphql
  src/index.ts
  test/api/mapping/support/commonPushTestsTest.ts
Labels: auto-merge:on-approve
