Repository atomist/sdm, pull requests merged in 2018-12, with the labels that each got.

#591 Polishing: use readonly arrays
  lib/api/machine/ListenerRegistrationManager.ts
  lib/api/machine/SoftwareDeliveryMachine.ts
Labels: auto-merge:on-approve, changelog:changed

#594 Run PushMappings sequentially
  lib/api/mapping/GoalSetter.ts
  lib/api/mapping/support/PushRules.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#595 Add support for trigger listeners
  lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  lib/api-helper/machine/ListenerRegistrationManagerSupport.ts
  lib/api/listener/TriggeredListener.ts
  lib/api/machine/ListenerRegistrationManager.ts
  lib/api/registration/TriggeredListenerRegistration.ts
  package-lock.json
  package.json
  test/api-helper/machine/AbstractSoftwareDeliveryMachine.test.ts
Labels: auto-merge:on-approve, changelog:added

#597 Add `Queue` goal to queue goal sets
  lib/api-helper/goal/chooseAndSetGoals.ts
  lib/api-helper/goal/storeGoals.ts
  lib/api-helper/listener/goalSetListener.ts
  lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  lib/api/goal/SdmGoalSetMessage.ts
  lib/api/goal/common/Queue.ts
  lib/api/goal/common/createGoal.ts
  lib/graphql/query/InProcessSdmGoalSets.graphql
  lib/graphql/query/SdmGoalByGoalSetIdAndUniqueName.graphql
  lib/graphql/query/SdmGoalSetForId.graphql
  lib/graphql/schema.json
  lib/graphql/subscription/OnAnySdmGoalSet.graphql
  test/api-helper/goal/storeGoals.test.ts
  test/api/goal/common/Queue.test.ts
  test/api/goal/common/createGoal.test.ts
Labels: changelog:added

#613 Add dryRun flag to CodeTransform invocations
  lib/api-helper/command/transform/chattyDryRunAwareEditor.ts
  lib/api-helper/command/transform/chattyEditor.ts
  lib/api-helper/machine/HandlerRegistrationManagerSupport.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api-helper/misc/child_process.ts
  lib/api-helper/misc/credentials/toToken.ts
  lib/api-helper/misc/spawned.ts
  lib/api-helper/pushtest/materialChangeTest.ts
  lib/api/command/target/BitBucketRepoTargets.ts
  lib/api/command/target/GitHubRepoTargets.ts
  lib/api/mapping/support/commonPushTests.ts
  lib/api/registration/AutoInspectRegistration.ts
  test/api/registration/commandRegistration.test.ts
Labels: auto-merge:on-approve, changelog:added

#615 Add helpers for `doWithRepos` and `doWithProject`
  lib/api-helper/project/withProject.ts
  lib/api-helper/project/withRepos.ts
  test/api-helper/project/withProject.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#617 Add project to invocation
  lib/api-helper/project/withProject.ts
  test/api-helper/project/withProject.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#620 Provide spawnLog with consistent spawn interface
  lib/api-helper/command/transform/spawnCodeTransform.ts
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/misc/child_process.ts
  lib/api-helper/project/withProject.ts
  test/api-helper/misc/child_process.test.ts
  test/api-helper/project/withProject.test.ts
Labels: auto-merge:on-approve, changelog:added

#618 Add exec and spawn to doWithProject callback
  lib/api-helper/command/transform/spawnCodeTransform.ts
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api-helper/misc/child_process.ts
  lib/api-helper/project/withProject.ts
  test/api-helper/misc/child_process.test.ts
  test/api-helper/project/withProject.test.ts
Labels: auto-merge:on-approve, changelog:added

#625 Introduce LazyProjectLoader and LazyProject interfaces
  lib/api-helper/goal/executeDeploy.ts
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/goal/executeUndeploy.ts
  lib/api-helper/listener/createPushImpactListenerInvocation.ts
  lib/api-helper/listener/executeAutoInspects.ts
  lib/api-helper/listener/executeAutofixes.ts
  lib/api-helper/listener/executeCancel.ts
  lib/api-helper/listener/executeFingerprinting.ts
  lib/api-helper/listener/executePushImpact.ts
  lib/api-helper/listener/executeVerifyEndpoint.ts
  lib/api-helper/project/GitHubLazyProjectLoader.ts
  lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
  lib/api/goal/GoalInvocation.ts
  lib/spi/project/LazyProjectLoader.ts
  test/api-helper/goal/executeGoal.test.ts
  test/api-helper/listener/executeAutoInspect.test.ts
  test/api-helper/listener/executeAutofixes.test.ts
  test/api-helper/listener/executeCancel.test.ts
  test/api-helper/project/GitHubLazyProjectLoader.test.ts
  test/api/goal/GoalWithFulfillment.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, breaking, changelog:changed

#630 Allow state computation in push rule evaluation
  lib/api/dsl/goalContribution.ts
  lib/api/dsl/goalDsl.ts
  test/api/dsl/goalContribution.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#632 Rename enrichInvocation to attachFact
  lib/api/dsl/goalContribution.ts
  test/api/dsl/goalContribution.test.ts
Labels: changelog:changed

#636 Add `targets.branch` to `CodeTransform` targeting
  lib/api/command/target/BitBucketRepoTargets.ts
  lib/api/command/target/GitHubRepoTargets.ts
  package-lock.json
  package.json
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#639 Update doc on goal execution listener
  lib/api/machine/ListenerRegistrationManager.ts
Labels: changelog:fixed
