Repository atomist/sdm, pull requests merged in 2018-10, with the labels that each got.

#543 Add tags to ExtensionPack metadata
  lib/api-helper/misc/extensionPack.ts
  lib/api/machine/ExtensionPack.ts
  test/api-helper/misc/extensionPack.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#545 Remove SDM-level goal methods
  lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  lib/api-helper/machine/ListenerRegistrationManagerSupport.ts
  lib/api/machine/ListenerRegistrationManager.ts
  lib/api/machine/SoftwareDeliveryMachine.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:removed

#546 Remove old style registration methods
  lib/api-helper/listener/executeAutofixes.ts
  lib/api/dsl/goalContribution.ts
  lib/api/goal/GoalWithFulfillment.ts
  lib/api/goal/Goals.ts
  lib/api/goal/common/AutoCodeInspection.ts
  lib/api/goal/common/Autofix.ts
  lib/api/goal/common/Fingerprint.ts
  lib/api/goal/common/Locking.ts
  lib/api/goal/common/PushImpact.ts
  lib/api/machine/GoalDrivenMachine.ts
  lib/api/machine/wellKnownGoals.ts
  test/api/dsl/goalContribution.test.ts
  test/api/goal/Goals.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:removed

#547 Re-export client exports used by SDMs
  lib/api-helper/code/autofix/spawnedCommandAutofix.ts
  lib/api-helper/code/review/patternMatchReviewer.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api-helper/misc/slack/messages.ts
  lib/api-helper/misc/spawned.ts
  lib/api/command/generator/SeedDrivenGeneratorParametersSupport.ts
  lib/api/command/target/BitBucketRepoTargets.ts
  lib/api/command/target/GitHubRepoTargets.ts
  lib/api/configuration/exports.ts
  lib/api/context/exports.ts
  lib/api/machine/RepoTargets.ts
  lib/api/mapping/support/commonPushTests.ts
  lib/api/project/exports.ts
  lib/api/registration/exports.ts
  lib/api/registration/transformUtils.ts
  package-lock.json
  package.json
  test/api-helper/listener/executeAutoInspect.test.ts
  test/api-helper/listener/executeAutofixes.test.ts
  test/api-helper/misc/project/filteredView.test.ts
  test/api-helper/misc/spawned.test.ts
  test/api-helper/project/lazyProjectLoader.test.ts
  test/api/registration/toScalarProjectEditor.test.ts
Labels: auto-merge:on-approve, breaking, changelog:added

#556 Add mock support
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/goal/mock.ts
  lib/api-helper/testsupport/fakePush.ts
  test/api-helper/goal/executeGoal.test.ts
  test/api-helper/goal/mock.test.ts
Labels: auto-merge:on-approve

#559 Add fetchGoalsFromPush method to read goals from subscription
  lib/api-helper/goal/fetchGoalsOnCommit.ts
  test/api-helper/goal/fetchGoalsOnCommit.test.ts
  test/api-helper/goal/mock.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#560 Add createPredicatedGoal
  lib/api/goal/GoalWithFulfillment.ts
  lib/api/goal/common/createGoal.ts
  package-lock.json
Labels: auto-merge-method:squash, changelog:added

#558 Expose structure of push tests and push rules
  lib/api-helper/dsl/buildDsl.ts
  lib/api-helper/dsl/deployDsl.ts
  lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  lib/api/dsl/allOf.ts
  lib/api/dsl/goalContribution.ts
  lib/api/mapping/GoalSetter.ts
  lib/api/mapping/Mapping.ts
  lib/api/mapping/PredicateMapping.ts
  lib/api/mapping/PushMapping.ts
  lib/api/mapping/PushTest.ts
  lib/api/mapping/support/PushRule.ts
  lib/api/mapping/support/PushRules.ts
  lib/api/mapping/support/predicateUtils.ts
  lib/api/mapping/support/pushTestUtils.ts
  test/api/dsl/goalContribution.test.ts
  test/api/dsl/whenPushSatisfies.test.ts
  test/api/mapping/introspectPushMap.test.ts
  test/api/mapping/predicateMapping.test.ts
  test/api/mapping/predictGoals.ts
  test/api/mapping/support/pushRules.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#561 Add commit-images link to GraphQL
  lib/api-helper/goal/executeDeploy.ts
  lib/graphql/fragment/PushFields.graphql
  lib/graphql/query/CommitForSdmGoal.graphql
Labels: auto-merge:on-approve, changelog:added
