Repository atomist/sdm, pull requests merged in 2018-09, with the labels that each got.

#501 Remove unimplemented property observesOnly
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api/machine/GoalDrivenMachine.ts
  test/api-helper/misc/extensionPack.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:changed

#505 Rename newRepoWithCode to firstPush
  CHANGELOG.md
  src/api-helper/machine/ListenerRegistrationManagerSupport.ts
  src/api/listener/RepoCreationListener.ts
  src/api/machine/ListenerRegistrationManager.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#504 Allow goals to receive implementations and listeners
  package-lock.json
  package.json
  src/api-helper/goal/DefaultGoalImplementationMapper.ts
  src/api-helper/goal/chooseAndSetGoals.ts
  src/api-helper/goal/executeGoal.ts
  src/api-helper/goal/storeGoals.ts
  src/api-helper/listener/executeAutoInspects.ts
  src/api-helper/listener/executeAutofixes.ts
  src/api-helper/listener/executeFingerprinting.ts
  src/api-helper/listener/executePushReactions.ts
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api-helper/test/fakeGoalInvocation.ts
  src/api-helper/voter/githubTeamVoter.ts
  src/api/goal/GoalInvocation.ts
  src/api/goal/GoalWithFulfillment.ts
  src/api/goal/Goals.ts
  src/api/goal/SdmGoalMessage.ts
  src/api/goal/common/Autofix.ts
  src/api/goal/common/CodeInspects.ts
  src/api/goal/common/Fingerprint.ts
  src/api/goal/common/PushImpact.ts
  src/api/goal/support/GoalImplementationMapper.ts
  src/api/machine/GoalDrivenMachine.ts
  src/api/machine/SoftwareDeliveryMachine.ts
  src/api/machine/SoftwareDeliveryMachineOptions.ts
  src/api/machine/registrable.ts
  src/index.ts
  src/pack/well-known-goals/addWellKnownGoals.ts
  src/pack/well-known-goals/commonGoals.ts
  src/pack/well-known-goals/httpServiceGoals.ts
  src/pack/well-known-goals/libraryGoals.ts
  test/api-helper/listener/executeAutoInspect.test.ts
  test/api-helper/listener/executeAutofixes.test.ts
  test/api-helper/listener/executePushReactions.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#500 Starting point should be able to handle a Promise returning function
  package-lock.json
  src/api-helper/command/generator/generatorCommand.ts
  src/api-helper/machine/handlerRegistrations.ts
  src/api/registration/GeneratorRegistration.ts
  src/api/registration/ParametersDefinition.ts
  test/api/registration/commandRegistration.test.ts
Labels: auto-merge-method:squash, changelog:added, enhancement

#507 Goal names are not automatically generated based on source code location
  src/api-helper/goal/DefaultGoalImplementationMapper.ts
  src/api-helper/goal/executeGoal.ts
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api/goal/Goal.ts
  src/api/goal/GoalInvocation.ts
  src/api/goal/GoalNameGenerator.ts
  src/api/goal/GoalWithFulfillment.ts
  src/api/goal/common/AutoCodeInspection.ts
  src/api/goal/common/Autofix.ts
  src/api/goal/common/Build.ts
  src/api/goal/common/Fingerprint.ts
  src/api/goal/common/PushImpact.ts
  src/api/machine/Registerable.ts
  src/index.ts
  test/api/goal/GoalNameGenerator.test.ts
Labels: auto-merge-method:squash, changelog:added

#513 Pass depth down to `git clone` in order to correctly diff the changes
  package-lock.json
  package.json
  src/api-helper/goal/DefaultGoalImplementationMapper.ts
  src/api-helper/goal/chooseAndSetGoals.ts
  src/api-helper/listener/createPushImpactListenerInvocation.ts
  src/api-helper/listener/executeAutoInspects.ts
  src/api-helper/listener/executeAutofixes.ts
  src/api-helper/listener/executeFingerprinting.ts
  src/api-helper/listener/executePushReactions.ts
  src/api-helper/misc/git/filesChangedSince.ts
  src/api-helper/project/cloningProjectLoader.ts
  src/api-helper/test/fakeGoalInvocation.ts
  src/api/goal/Goal.ts
  src/spi/project/ProjectLoader.ts
  test/api-helper/misc/git/filesChangedSince.test.ts
  test/api-helper/project/lazyProjectLoader.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:fixed

#519 Fingerprint listeners should get all of the fingerprints delivered to…
  src/api-helper/listener/executeFingerprinting.ts
  src/api/listener/FingerprintListener.ts
Labels: auto-merge-method:merge, changelog:changed

#520 Prepare to hook in client startup events
  package-lock.json
  src/api-helper/listener/executeAutofixes.ts
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api-helper/machine/ListenerRegistrationManagerSupport.ts
  src/api-helper/misc/git/filesChangedSince.ts
  src/api-helper/project/LazyProjectLoader.ts
  src/api-helper/test/fakeGoalInvocation.ts
  src/api/context/AdminCommunicationContext.ts
  src/api/goal/common/PushImpact.ts
  src/api/listener/StartupListener.ts
  src/api/machine/ListenerRegistrationManager.ts
  src/api/machine/SoftwareDeliveryMachineOptions.ts
  src/index.ts
  test/api-helper/TestSoftwareDeliveryMachine.ts
  test/api-helper/misc/git/filesChangedSince.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#518 Deprecate per SDM methods related to specific goals
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api/machine/ListenerRegistrationManager.ts
  src/api/machine/SoftwareDeliveryMachine.ts
  src/api/registration/ProjectInvariantRegistration.ts
  src/index.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:deprecated

#533 New states for stopped and canceled goals
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/goal/storeGoals.ts
  lib/api-helper/listener/executeAutoInspects.ts
  lib/api-helper/listener/executeAutofixes.ts
  lib/api-helper/listener/executeVerifyEndpoint.ts
  lib/api/goal/ExecuteGoalResult.ts
  lib/api/goal/Goal.ts
  lib/api/machine/wellKnownGoals.ts
  lib/graphql/schema.json
  package-lock.json
  package.json
  test/api-helper/listener/executeAutoInspect.test.ts
  test/api-helper/listener/executeAutofixes.test.ts
  test/api-helper/listener/executePushReactions.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#541 Remove well known goals
  lib/pack/well-known-goals/addWellKnownGoals.ts
  lib/pack/well-known-goals/commonGoals.ts
  lib/pack/well-known-goals/httpServiceGoals.ts
  lib/pack/well-known-goals/libraryGoals.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:removed
