Repository atomist/sdm, pull requests merged in 2018-11, with the labels that each got.

#566 Add WellKnownGoals
  lib/api/machine/WellKnownGoals.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#572 Add support for canceling goals
  lib/api-helper/listener/executeCancel.ts
  lib/api/goal/GoalWithFulfillment.ts
  lib/api/goal/common/AutoCodeInspection.ts
  lib/api/goal/common/Autofix.ts
  lib/api/goal/common/Cancel.ts
  lib/api/goal/common/Fingerprint.ts
  lib/api/goal/common/PushImpact.ts
  lib/graphql/query/SdmGoalsByShaAndBranch.graphql
  package-lock.json
  package.json
  test/api-helper/listener/executeCancel.test.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added

#573 Add review listeners that set goal result state
  .gitignore
  .npmignore
  graphql.schema.json
  lib/api-helper/code/review/goalReviewListener.ts
  lib/api-helper/goal/storeGoals.ts
  lib/typings/.gitignore
  package-lock.json
  package.json
  schema.json
  test/api-helper/code/review/goalReviewListener.test.ts
Labels: auto-merge:on-approve, changelog:added

#586 Make `code` on `ExecuteGoalResult` optional
  lib/api-helper/goal/executeGoal.ts
  lib/api/goal/ExecuteGoalResult.ts
  test/api-helper/goal/executeGoal.test.ts
  test/api/goal/ExecuteGoalResult.test.ts
Labels: auto-merge:on-approve, changelog:changed
