Repository atomist/sdm, pull requests merged in 2018-07, with the labels that each got.

#424 Rename "editor" to "codeTransform" for clarity
  src/api-helper/code/autofix/spawnedCommandAutofix.ts
  src/api-helper/command/editor/localCommandsCodeTransform.ts
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api-helper/machine/HandlerRegistrationManagerSupport.ts
  src/api-helper/machine/ListenerRegistrationManagerSupport.ts
  src/api-helper/machine/handlerRegistrations.ts
  src/api-helper/misc/extensionPack.ts
  src/api/machine/CommandRegistrationManager.ts
  src/api/machine/ListenerRegistrationManager.ts
  src/api/registration/AutofixRegistration.ts
  src/api/registration/CodeTransformRegistration.ts
  src/api/registration/ProjectOperationRegistration.ts
  src/index.ts
  test/api-helper/listener/relevantCodeActionsTest.ts
  test/api/registration/commandRegistrationTest.ts
Labels: breaking, changelog:fixed

#425 Allow generator registrations to specify a starting point
  src/api-helper/command/generator/generatorCommand.ts
  src/api-helper/machine/handlerRegistrations.ts
  src/api/command/generator/SeedDrivenGeneratorParametersSupport.ts
  src/api/registration/GeneratorRegistration.ts
  test/api/registration/commandRegistrationTest.ts
Labels: changelog:added

#426 Rename to GoalInvocation; deprecate status
  package-lock.json
  src/api-helper/command/generator/generatorCommand.ts
  src/api-helper/goal/chooseAndSetGoals.ts
  src/api-helper/goal/executeBuild.ts
  src/api-helper/goal/executeDeploy.ts
  src/api-helper/goal/executeGoal.ts
  src/api-helper/goal/executeUndeploy.ts
  src/api-helper/goal/reportGoalError.ts
  src/api-helper/goal/sdmGoal.ts
  src/api-helper/goal/storeGoals.ts
  src/api-helper/listener/createPushImpactListenerInvocation.ts
  src/api-helper/listener/executeAutofixes.ts
  src/api-helper/listener/executePushReactions.ts
  src/api-helper/listener/executeReview.ts
  src/api-helper/listener/executeVerifyEndpoint.ts
  src/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  src/api-helper/machine/HandlerRegistrationManagerSupport.ts
  src/api-helper/machine/handlerRegistrations.ts
  src/api-helper/test/fakeRunWithLogContext.ts
  src/api/goal/ExecuteGoalWithLog.ts
  src/api/goal/GoalInvocation.ts
  src/api/goal/SdmGoal.ts
  src/api/goal/SdmGoalEvent.ts
  src/api/goal/SdmGoalMessage.ts
  src/api/goal/support/SdmGoalImplementationMapper.ts
  src/api/goal/support/executeSendMessageToSlack.ts
  src/api/machine/GoalDrivenMachine.ts
  src/graphql/fragment/PushFields.graphql
  src/graphql/fragment/SdmGoalFields.graphql
  src/index.ts
  src/spi/repo-ref/RepoRefResolver.ts
  test/api-helper/goal/executeGoalTest.ts
Labels: changelog:deprecated

#431 Do not memoize pre-emptively
  src/api/mapping/support/PushRule.ts
  src/api/mapping/support/pushTestUtils.ts
Labels: changelog:removed, enhancement

#435 Generators no longer require base parameters
  CHANGELOG.md
  package-lock.json
  src/api-helper/command/generator/generatorCommand.ts
  src/api-helper/machine/handlerRegistrations.ts
  src/api/registration/CommandHandlerRegistration.ts
  src/api/registration/GeneratorRegistration.ts
  src/api/registration/ParametersDefinition.ts
  test/api/registration/commandRegistrationTest.ts
Labels: atomist:merge-on-approve

#437 Add DSL for creating Goals
  src/api/goal/Goals.ts
  test/api/goal/GoalsTest.ts
Labels: atomist:merge-on-approve, changelog:added, enhancement

#459 Add predicate mapping cost analyzer
  src/api/mapping/support/PredicateMappingCostAnalyzer.ts
  src/api/mapping/support/defaultPredicateMappingCostAnalyzer.ts
  src/api/mapping/support/predicateUtils.ts
  src/api/mapping/support/projectPredicateUtils.ts
  src/api/mapping/support/pushTestUtils.ts
  test/api/mapping/support/projectPredicateUtilsTest.ts
  test/api/mapping/support/pushTestUtilsTest.ts
Labels: atomist:merge-on-approve, changelog:added

#461 Collect names of Goal and Goals instances in contributor model
  src/api/dsl/goalContribution.ts
  src/api/dsl/goalDsl.ts
  src/api/goal/common/MessageGoal.ts
  src/api/machine/wellKnownGoals.ts
  test/api/dsl/goalContributionTest.ts
Labels: atomist:merge-on-approve, changelog:added, enhancement
