Repository atomist/sdm, pull requests merged in 2019-05, with the labels that each got.

#733 Add support for reading project configuration from a yaml file
  lib/api-helper/project/configuration/projectConfiguration.ts
  package-lock.json
  package.json
  test/api-helper/project/configuration/projectConfiguration.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#734 Deprecate deployers
  lib/api-helper/goal/executeDeploy.ts
  lib/api-helper/goal/executeUndeploy.ts
  lib/api/listener/ArtifactListener.ts
  lib/api/machine/SoftwareDeliveryMachineOptions.ts
  lib/spi/artifact/ArtifactStore.ts
  lib/spi/deploy/Deployer.ts
  lib/spi/deploy/Deployment.ts
  lib/spi/deploy/Target.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:changed, changelog:deprecated

#737 Add progressLog to CodeInspection and CodeTransform
  lib/api-helper/command/transform/codeTransformWrapping.ts
  lib/api-helper/listener/executeAutoInspects.ts
  lib/api-helper/machine/adaptHandleCommand.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api/registration/PushAwareParametersInvocation.ts
  test/api-helper/machine/adaptHandleCommand.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#741 Improvements to message sending protocol
  lib/api-helper/command/createCommand.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api/context/parameterPrompt.ts
  lib/api/listener/CommandListener.ts
  lib/api/registration/CommandRegistration.ts
  package-lock.json
  package.json
  test/api/registration/commandRegistration.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added, enhancement
