Repository atomist/sdm, pull requests merged in 2019-04, with the labels that each got.

#697 Add project-aware goal invocation converter
  lib/api-helper/project/withProject.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:added

#703 Clean up push impact invocation
  lib/api/registration/PushImpactListenerRegistration.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, breaking, changelog:changed

#708 Make setGoalsWhen respect enclosing PushTest
  lib/api/dsl/goalDsl.ts
  test/api/dsl/goalContribution.test.ts
Labels: auto-merge-method:squash, auto-merge:on-check-success, changelog:fixed

#713 Allow transform presentation on autofix goal
  lib/api-helper/command/generator/generatorCommand.ts
  lib/api-helper/listener/executeAutofixes.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api/goal/common/Autofix.ts
  lib/api/listener/CommandListener.ts
  lib/api/registration/CodeTransformRegistration.ts
  lib/api/registration/GeneratorRegistration.ts
  test/api-helper/listener/executeAutofixes.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve
