Repository atomist/sdm, pull requests merged in 2019-02, with the labels that each got.

#666 Provide a useful implementation of onTransformResults
  lib/api-helper/command/transform/onTransformResult.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, changelog:added, enhancement

#674 Accept extensions starting with . in isMaterialChange
  lib/api-helper/misc/git/filesChangedSince.ts
  test/api-helper/pushtest/materialChangeTest.test.ts
Labels: auto-merge:on-approve, changelog:changed

#676 Add conditional command registration
  lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  lib/api/registration/CommandRegistration.ts
Labels: auto-merge-method:squash, changelog:added, enhancement

#678 Introduce goal signing and verification
  lib/api-helper/command/generator/generatorCommand.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api/machine/SigningKeys.ts
  lib/api/machine/SoftwareDeliveryMachineOptions.ts
  lib/graphql/fragment/SdmGoalFields.graphql
  lib/graphql/fragment/SdmGoalWithPushFields.graphql
  lib/graphql/query/SdmGoalsByShaAndBranch.graphql
  lib/graphql/schema.json
  lib/spi/credentials/CredentialsResolver.ts
  test/api-helper/machine/handlerRegistration.test.ts
Labels: auto-merge:on-approve, changelog:added, enhancement

#683 Adds Gitlab repo targets for commands
  lib/api/command/target/GitlabRepoTargets.ts
Labels: auto-merge:on-approve
