Repository atomist/sdm, pull requests merged in 2019-01, with the labels that each got.

#652 Populate the SHA on projects when loading them.
  lib/api-helper/project/cloningProjectLoader.ts
Labels: auto-merge:on-approve, changelog:changed

#650 If an autofix error includes some output, print it to the progress log
  lib/api-helper/listener/executeAutofixes.ts
Labels: changelog:added

#644 Use TypeScript Record type to enforce matching of parameter interface with definitions
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api/registration/CommandRegistration.ts
  lib/api/registration/ParametersDefinition.ts
  test/api/registration/commandRegistration.test.ts
Labels: auto-merge:on-approve, changelog:changed, enhancement

#656 Make goal launching more pluggable
  lib/api/goal/support/GoalLauncher.ts
  lib/api/machine/SoftwareDeliveryMachineOptions.ts
  package-lock.json
  package.json
Labels: auto-merge:on-approve, changelog:changed

#585 Stream files during code transform
  lib/api-helper/project/fileCopy.ts
  test/api-helper/project/fileCopy.test.ts
Labels: changelog:added

#658 Add PreferenceStore interface
  lib/api-helper/goal/chooseAndSetGoals.ts
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/listener/createPushImpactListenerInvocation.ts
  lib/api-helper/listener/executeAutoInspects.ts
  lib/api-helper/listener/executeFingerprinting.ts
  lib/api-helper/listener/executeVerifyEndpoint.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
  lib/api-helper/testsupport/fakeCommandListenerInvocation.ts
  lib/api-helper/testsupport/fakeGoalInvocation.ts
  lib/api-helper/testsupport/fakePush.ts
  lib/api/context/SdmContext.ts
  lib/api/context/preferenceStore.ts
  lib/api/machine/SoftwareDeliveryMachineOptions.ts
  package-lock.json
  test/api/mapping/predictGoals.ts
Labels: auto-merge:on-approve, changelog:added

#659 Add branchAwareCodeTransform to make it target branch aware
  lib/api-helper/command/transform/codeTransformWrapping.ts
  lib/graphql/query/BranchForName.graphql
Labels: changelog:added

#661 Support parameter prompting from command listeners
  lib/api-helper/goal/chooseAndSetGoals.ts
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api-helper/testsupport/fakeCommandListenerInvocation.ts
  lib/api/context/SdmContext.ts
  lib/api/context/parameterPrompt.ts
  lib/api/context/preferenceStore.ts
  lib/api/goal/support/GoalScheduler.ts
  lib/api/listener/CommandListener.ts
  lib/api/machine/SoftwareDeliveryMachineOptions.ts
  lib/api/registration/ParametersDefinition.ts
  lib/graphql/query/BranchForName.graphql
  package-lock.json
  package.json
  test/api/context/parameterPrompt.test.ts
Labels: auto-merge:on-approve, changelog:added, enhancement

#663 Improve startingPoint handling in generators
  lib/api-helper/command/generator/generatorCommand.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api/registration/GeneratorRegistration.ts
Labels: auto-merge:on-approve, changelog:changed

#665 Enhance the typedoc within CodeTransformRegistration
  lib/api/registration/CodeTransformRegistration.ts
Labels: auto-merge-method:squash, auto-merge:on-check-success, changelog:added
