Repository atomist/sdm, pull requests merged in 2020-02, with the labels that each got.

#797 CachingProjectLoader should respect clone parameters
  lib/api-helper/project/CachingProjectLoader.ts
  lib/api-helper/project/support/cacheKey.ts
  package-lock.json
  package.json
  test/api-helper/project/cachingProjectLoader.test.ts
Labels: auto-branch-delete:on-close, changelog:fixed

#808 Add support for skill output
  lib/api-helper/goal/chooseAndSetGoals.ts
  lib/api-helper/goal/executeGoal.ts
  lib/api-helper/listener/createPushImpactListenerInvocation.ts
  lib/api-helper/listener/executeAutoInspects.ts
  lib/api-helper/machine/handlerRegistrations.ts
  lib/api-helper/project/ProjectListenerInvokingProjectLoader.ts
  lib/api-helper/testsupport/fakeCommandListenerInvocation.ts
  lib/api-helper/testsupport/fakeGoalInvocation.ts
  lib/api-helper/testsupport/fakePush.ts
  lib/api/context/SdmContext.ts
  lib/api/context/skillContext.ts
  lib/api/mapping/goalTest.ts
  lib/api/mapping/outputTest.ts
  lib/graphql/schema.json
  lib/graphql/subscription/OnAnySkillOutput.graphql
  test/api/context/skillContext.test.ts
  test/api/mapping/predictGoals.ts
Labels: auto-branch-delete:on-close, auto-merge-method:merge, auto-merge:on-check-success, changelog:added

#817 K8s cleanup
  lib/api-helper/goal/sdmGoal.ts
  lib/api-helper/goal/storeGoals.ts
  lib/api-helper/misc/project/filteredView.ts
  lib/api-helper/project/GitHubLazyProjectLoader.ts
  lib/api-helper/project/configuration/projectConfiguration.ts
  lib/api/goal/GoalWithFulfillment.ts
  lib/api/mapping/goalTest.ts
  lib/core/goal/cache/goalCaching.ts
  lib/core/goal/container/container.ts
  lib/core/goal/container/util.ts
  lib/core/goal/skillOutput.ts
  lib/core/log/RolarProgressLog.ts
  lib/core/pack/k8s/container.ts
  lib/core/pack/k8s/deploy/data.ts
  lib/core/pack/k8s/kubernetes/application.ts
  lib/core/pack/k8s/kubernetes/apply.ts
  lib/core/pack/k8s/kubernetes/delete.ts
  lib/core/pack/k8s/kubernetes/deployment.ts
  lib/core/pack/k8s/kubernetes/fetch.ts
  lib/core/pack/k8s/kubernetes/ingress.ts
  lib/core/pack/k8s/kubernetes/namespace.ts
  lib/core/pack/k8s/kubernetes/role.ts
  lib/core/pack/k8s/kubernetes/roleBinding.ts
  lib/core/pack/k8s/kubernetes/secret.ts
  lib/core/pack/k8s/kubernetes/service.ts
  lib/core/pack/k8s/kubernetes/serviceAccount.ts
  lib/core/pack/k8s/scheduler/KubernetesFulfillmentGoalScheduler.ts
  lib/core/pack/k8s/scheduler/KubernetesGoalScheduler.ts
  lib/core/pack/k8s/support/error.ts
  lib/core/pack/k8s/support/retry.ts
  lib/core/pack/k8s/sync/goals.ts
  lib/core/pack/k8s/sync/sync.ts
  test/api-helper/goal/DefaultGoalImplementationMapper.test.ts
  test/api-helper/listener/executeCancel.test.ts
  test/api-helper/misc/child_process.test.ts
  test/api-helper/misc/job/createJob.test.ts
  test/api-helper/project/GitHubLazyProjectLoader.test.ts
  test/api-helper/pushtest/materialChangeTest.test.ts
  test/api/goal/GoalNameGenerator.test.ts
  test/core/goal/container/container.test.ts
  test/core/goal/container/docker.test.ts
  test/core/mapping/pushtest/toPublicRepo.test.ts
  test/core/pack/gcp/cache.test.ts
  test/core/pack/k8s/container.test.ts
  test/core/pack/k8s/kubernetes/api.test.ts
  test/core/pack/k8s/kubernetes/application.test.ts
  test/core/pack/k8s/kubernetes/delete.test.ts
  test/core/pack/k8s/kubernetes/fetch.test.ts
  test/core/pack/k8s/scheduler/KubernetesFulfillmentGoalScheduler.test.ts
  test/core/pack/k8s/support/error.test.ts
  test/core/pack/k8s/sync/diff.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:changed
