Repository atomist/sdm, pull requests merged in 2020-03, with the labels that each got.

#818 Kill timed out container goals
  lib/api-helper/goal/sdmGoal.ts
  lib/api-helper/misc/child_process.ts
  lib/api-helper/misc/spawned.ts
  lib/core/pack/k8s/container.ts
  lib/core/pack/k8s/scheduler/KubernetesGoalScheduler.ts
  lib/core/pack/k8s/sync/startup.ts
  test/core/pack/k8s/container.test.ts
  test/core/pack/k8s/scheduler/KubernetesGoalScheduler.test.ts
Labels: auto-merge-method:merge, auto-merge:on-approve, changelog:fixed

#820 K8s patch strategy and simplify KubernetesApplication
  lib/core/pack/k8s/deploy/deploy.ts
  lib/core/pack/k8s/deploy/externalUrls.ts
  lib/core/pack/k8s/kubernetes/deployment.ts
  lib/core/pack/k8s/kubernetes/ingress.ts
  lib/core/pack/k8s/kubernetes/namespace.ts
  lib/core/pack/k8s/kubernetes/patch.ts
  lib/core/pack/k8s/kubernetes/request.ts
  lib/core/pack/k8s/kubernetes/role.ts
  lib/core/pack/k8s/kubernetes/roleBinding.ts
  lib/core/pack/k8s/kubernetes/secret.ts
  lib/core/pack/k8s/kubernetes/service.ts
  lib/core/pack/k8s/kubernetes/serviceAccount.ts
  test/core/pack/k8s/deploy/externalUrls.test.ts
  test/core/pack/k8s/kubernetes/deployment.test.ts
  test/core/pack/k8s/kubernetes/ingress.test.ts
  test/core/pack/k8s/kubernetes/patch.test.ts
Labels: auto-branch-delete:on-merge, auto-merge-method:merge, auto-merge:on-approve, changelog:added

#822 Default registration and push test for side effect
  lib/api-helper/goal/DefaultGoalImplementationMapper.ts
  lib/api-helper/goal/chooseAndSetGoals.ts
  lib/api-helper/machine/AbstractSoftwareDeliveryMachine.ts
  lib/api/goal/support/GoalImplementationMapper.ts
Labels: auto-branch-delete:on-merge, auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#823 Add support for reading GitHub app tokens
  lib/core/pack/k8s/sync/repo.ts
  test/core/pack/k8s/sync/repo.test.ts
Labels: auto-branch-delete:on-merge, auto-merge-method:merge, auto-merge:on-approve, changelog:changed

#829 Query for credentials each k8s repo sync
  lib/core/pack/k8s/sync/repo.ts
  lib/core/pack/k8s/sync/startup.ts
  test/core/pack/k8s/sync/repo.test.ts
Labels: auto-branch-delete:on-merge, auto-merge-method:merge, auto-merge:on-approve

#830 Query k8s sync repo creds in worker
  lib/core/pack/k8s/sync/repo.ts
  lib/core/pack/k8s/sync/startup.ts
  lib/core/pack/k8s/sync/sync.ts
  test/.gitignore
  test/core/pack/k8s/sync/repo.test.ts
  test/core/pack/k8s/sync/sync.test.ts
Labels: auto-branch-delete:on-merge, auto-merge-method:merge, auto-merge:on-approve, changelog:fixed
